### ISSUE TITLE
Problem with adding logic

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/making-tens#10]
The logic for making tens is that in order to add, say 3+8, I am forced to take 1 off of 3 so that it becomes a 2, then I can combine 2+8 to make 10, then add 1 to get 11. 3+8 will not combine unless they are in pieces that make a 10. 

The same logic is true for 30+80. In order to add these, I must make 100, which means I can add 20+80 to get 100, then add the remaining 10 to get 110. 

If I add 130+780, I must be forced to take off the 30 or 80 and break it up. Right now, I can simply drag one number on top of the other and they combine to make 910. 

![screen shot 2015-07-06 at 1 46 47 pm](https://cloud.githubusercontent.com/assets/7852916/8531599/d1798e2c-23e5-11e5-9fe0-14764edbb578.png)
![screen shot 2015-07-06 at 1 49 45 pm 2](https://cloud.githubusercontent.com/assets/7852916/8531622/ffdaf5c6-23e5-11e5-96a8-61ee3152e1f9.png)
![screen shot 2015-07-06 at 1 50 02 pm](https://cloud.githubusercontent.com/assets/7852916/8531627/02713ac0-23e6-11e5-952a-ae2307aa8e9e.png)

**Comment by AshrafSharf** [comment]
I have tested this scenario.The logic behaves as you have described. I think the issue got addressed as part of fixing another bug. Please have a relook.

**Comment by amanda-phet** [comment]
@bethstade Can you also look at this? I am not as familiar with the adding logic as you are. I believe this is fixed, but want to be sure it is still behaving as it should.

**Comment by bethstade** [comment]
just got email back (and back in colorado). I will check tomorrow.
Thanks.
Beth
I


----- Original Message -----From: Amanda McGarry <notifications@github.com>To: phetsims/making-tens <making-tens@noreply.github.com>Cc: bethstade <stadee@colorado.edu>Sent: Tue, 28 Jul 2015 22:32:15 -0000 (UTC)Subject: Re: [making-tens] Problem with adding logic (#10)

@bethstade Can you also look at this? I am not as familiar with the adding logic as you are. I believe this is fixed, but want to be sure it is still behaving as it should.
&mdash;Reply to this email directly or view it on GitHub.

**Comment by bethstade** [comment]
Do I need to be on campus to check the latest version?
I am just seeing dev.2 in PHet dev, which is pretty old.
Thanks!
Beth


----- Original Message -----From: Amanda McGarry <notifications@github.com>To: phetsims/making-tens <making-tens@noreply.github.com>Cc: bethstade <stadee@colorado.edu>Sent: Tue, 28 Jul 2015 22:32:17 -0000 (UTC)Subject: Re: [making-tens] Problem with adding logic (#10)

Assigned #10 to @bethstade.
&mdash;Reply to this email directly or view it on GitHub.

**Comment by ariel-phet** [comment]
@bethstade if you are on campus (or you VPN to campus) you can see an up to date version on http://phettest.colorado.edu/

**Comment by ariel-phet** [comment]
@bethstade you need to go to the "gitdev" section on phettest and then navigate to making tens

**Comment by bethstade** [comment]
thanks!

----- Original Message -----From: Ariel Paul <notifications@github.com>To: phetsims/making-tens <making-tens@noreply.github.com>Cc: bethstade <stadee@colorado.edu>Sent: Wed, 29 Jul 2015 18:26:45 -0000 (UTC)Subject: Re: [making-tens] Problem with adding logic (#10)

@bethstade you need to go to the "gitdev" section on phettest and then navigate to making tens
&mdash;Reply to this email directly or view it on GitHub.
