### ISSUE TITLE
Should exiting a game level and re-entering have state reset?

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/making-tens#100]
For example:
1. I enter the first level, and I'm given 2 + 4. Maybe I move a 1 from the 4 to the 2, making two 3s.
2. I hit the "back button", (to check?), then re-enter the first level.
3. It's now 6 + 4, with none of our progress saved.

Is this desirable/acceptable? I would have presumed it would be saved.

@amanda-phet, @bethstade and @ariel-phet opinions?

**Comment by bethstade** [comment]
This is the correct behavior.
We are just living in the moment.

**Comment by jonathanolson** [comment]
Sounds good, closing.
