### ISSUE TITLE
Level 6 "under hundreds" challenge

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/making-tens#106]
First of all, I can't seem to find detailed documentation on the ranges of what numbers should be. Is there a separate doc for that? (Checked specification doc and the logic doc).

I'm curious about the expected range of numbers, since the model as written is basically:
1. Generate 39 pairs of numbers where:
  a. The first number is between 10 and 48 (inclusive)
  b. The second number is between 10 and 49 (inclusive)
2. Grab a random pair from those, randomly switching the first and second number.

This noticeably:
1. Never includes a number 50+
2. Will never sum to 98 or 99

Is that by design?

**Comment by jonathanolson** [comment]
Also tagging @amanda-phet

**Comment by jonathanolson** [comment]
A fairly equivalent design is done with Level 7 "over hundreds".

**Comment by bethstade** [comment]
My original specification was:
Level 6 - Add double digit numbers whose sum is less than 100. Pick random double digit pairs whose sum is less than 100.

Pick 2 double digits between 11-88 inclusive.
Make sure sum is less than 100.
May or may not cross decades.

88 + 11
43 +31
25 + 63
15 + 47

NOT:
89 + 67
9 + 45
93 + 17
from https://docs.google.com/document/d/16ESluSvJBQ3aeIW_LT1IHKbDsy1suuS_AYk__xni_kk/edit

So just:
1. Pick A between 11 and 88 first number.
2. Then B is random number between 10 and (99 - A).

**Comment by bethstade** [comment]
Again from "Making Tens Game Sets"
Level 7 - Add double digit sums whose sums are greater than or equal to 100.

Pick any double digit numbers between 11 and 99 inclusive.  
Make sure sum is greater than or =  100.

87 + 67   
43 + 97
63 + 52

NOT:
8 + 97
104 + 28

**Comment by jonathanolson** [comment]
Thanks, I have the document reference now! I'll briefly re-review the implementation according to it.

**Comment by bethstade** [comment]
Hi Jon,
So glad you are going over the details.
I am trying to keep up.
I will stop by when on campus tomorrow.
Thanks!
Beth


----- Original Message -----From: Jonathan Olson <notifications@github.com>To: phetsims/making-tens <making-tens@noreply.github.com>Cc: bethstade <stadee@colorado.edu>Sent: Tue, 01 Mar 2016 00:55:57 -0000 (UTC)Subject: Re: [making-tens] Level 6 "under hundreds" challenge (#106)

Thanks, I have the document reference now! I'll briefly re-review the implementation according to it.
&mdash;Reply to this email directly or view it on GitHub.

**Comment by jonathanolson** [comment]
Sure, sounds great! I'll be available after developer meeting (11 or 12?) until ~3pm.

"Making Tens Game Sets" was perfect, I've added issues to address everything. We'll follow the general "enumerate all possibilities, then pick one uniformly" when possible, which should generally have the desired behavior.

Closing this issue, to handle with level/level-generation specific issues.
