### ISSUE TITLE
Aspect ratio change for paper numbers in the explore panel

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/making-tens#132]
Is the tweak in aspect ratio for the explore panel (~16% shorter to squish the numbers) part of the specification?

I'm personally in favor of the current appearance.

Current appearance:
![making-tens-aspect-ratio-different](https://cloud.githubusercontent.com/assets/480878/13419744/daaf09fe-df3d-11e5-889d-11f67f2ee2bf.PNG)

Appearance so that numbers have the same aspect ratio as in the play area:
![making-tens-aspect-ratio-same](https://cloud.githubusercontent.com/assets/480878/13419759/ee56e4d6-df3d-11e5-8493-5d0ab8be0c22.PNG)

**Comment by jonathanolson** [comment]
Tagging @amanda-phet also.

**Comment by bethstade** [comment]
I don't about the 16% squish. Was that something that come up with the new number font?

**Comment by jonathanolson** [comment]
> Was that something that came up with the new number font?

No clue. Should we keep the current appearance?

**Comment by bethstade** [comment]
Ariel, Do you know what the 16% squish is from?
I wonder if we thought that would make more of a tab at the bottom of the number?  
It doesn't appear to me to being doing much.

**Comment by ariel-phet** [comment]
@bethstade I think you might be misinterpreting the question. I believe this is just the appearance in the "tool panel" from which you drag the numbers out. It is really just a question of aesthetics there. 

I would say look at the first comment and just decide which look you like better for numbers in that tool panel. @jonathanolson commented that he preferred the current appearance in the panel. I am agnostic.

**Comment by bethstade** [comment]
I am fine with current appearance.

**Comment by jonathanolson** [comment]
Sounds good, closing.
