### ISSUE TITLE
Preferred stacking order

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/making-tens#150]
@amanda-phet and @bethstade, I was curious if there was a decision on what paper numbers should be in front of others.

Right now, dragged numbers are in front of non-dragged numbers (I believe, so what you drag is in front), but sometimes when you release that number, it can move behind other numbers (it was in front before), particularly if the released number is bigger than the in-front number.

The general (other-sim) behavior is to leave released numbers still in front.

This results in non-dragged single-digit numbers being in front of double-digit numbers, which are all in front of triple-digit numbers etc., like below:
![screen shot 2016-03-01 at 1 34 20 pm](https://cloud.githubusercontent.com/assets/480878/13441032/74dd06c4-dfb2-11e5-9c2a-e5ca7655777b.png)

Is the dragging working as expected?

**Comment by bethstade** [comment]
This was a solution to the problem of "lost" numbers.  If we keep the order (as in other sims) and allow a big number to stay on top, then the smaller numbers can get "lost" and unseen below when covered by the bigger numbers.  The solution was to have all the numbers remain in their own plane (singles on top of doubles, on top of triples) when they are not moved which results in smaller numbers "popping thru."  So yes, correct behavior.

**Comment by jonathanolson** [comment]
Sounds great, thanks!
