### ISSUE TITLE
PaperNumberModel trig conversion

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/making-tens#156]
In step(), it seems the current code:
```js
var stepAngle = Math.atan2( this.destination.y - this.position.y, this.destination.x - this.position.x );
var stepVector = Vector2.createPolar( thisModel.velocity * dt, stepAngle );
```
converts to an angle, and then creates a vector based on this angle.

In general, I'd recommend working just with vectors when possible, for instance:
```js
var stepVector = this.destination.minus( this.position ).setMagnitude( dt );
```
should be equivalent, will run faster if it's in a loop, and is easier to read.

**Comment by AshrafSharf** [comment]
Replaced createPolar and changed the code as below
```Javascript
var stepVector = this.destination.minus( this.position ).setMagnitude( thisModel.animationVelocity * dt );
```
