### ISSUE TITLE
Implement a boundary for numbers

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/making-tens#17]
Right now, it is possible to "lose" a number outside of the viewing port of the browser if I drag the cursor over far enough.
<img width="935" alt="screen shot 2015-07-09 at 4 31 49 pm" src="https://cloud.githubusercontent.com/assets/7852916/8608430/07f079ce-2658-11e5-8517-2b4a3a8e9ff6.png">

We discussed this at the 7/9 design meeting and decided that a boundary must be implemented. We'd like it to function so that the center point of any number can not move with the cursor beyond the viewing port of the browser. If the browser is resized to be smaller, the numbers will move in to be consistent with this rule. 

In the case that a number on the edge of the browser moves in so that it collides with another number, they may end up combining, and we are okay with that.

**Comment by AshrafSharf** [comment]
Fixed

**Comment by amanda-phet** [comment]
This seems to be functioning perfectly fine. 

I believe @bethstade wanted the numbers to be able to move slightly beyond the boundary that you've implemented. We described it as "the center point of any number can not move with the cursor beyond the viewing port". So basically, no more than 50% of the number can be dragged beyond the viewing port. As it functions now, 0% of the number can be dragged beyond the viewing port.

**Comment by AshrafSharf** [comment]
Now 50% of the number's size  can be dragged  beyond the boundary. Please verify

**Comment by amanda-phet** [comment]
It looks great and works well. Closing.
