### ISSUE TITLE
Multiple instances of bound functions

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/making-tens#175]
In MakingTensExploreScreenView, there are multiple instances of ```self.addUserCreatedNumberModelToExplorerView.bind( self )``` and ```self.canPlaceShape.bind( self )```.

This will create multiple different functions, and is generally recommended to just create one bound function and pass it to all three places (less memory/overhead, faster for the optimizer, and they will be the same object instead of different objects).

**Comment by AshrafSharf** [comment]
Multiple bound function Instances replaced with a single instance
