### ISSUE TITLE
Make total float

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/making-tens#18]
We would like to make the total on the Explore screen float so that as the browser is resized, it will always be in the top-left corner. @jonathanolson says this should be possible with scenery.

**Comment by amanda-phet** [comment]
@AshrafSharf Does this seem like it would be easy for you to implement?

**Comment by amanda-phet** [comment]
I've noticed it is responding to the viewport bounds, which is perfect. However, I think it should be placed more left, since the current placement is pretty close to the center. Here is the placement using the ?dev boundary: 
![screen shot 2015-08-31 at 2 15 29 pm](https://cloud.githubusercontent.com/assets/7852916/9589348/e5374d74-4fea-11e5-9eee-d303f811a2dd.png)

Can we place it more left? Like this: 
![screen shot 2015-08-31 at 2 18 28 pm](https://cloud.githubusercontent.com/assets/7852916/9589386/301c3fa2-4feb-11e5-9243-9c8f93e2d464.png)

**Comment by AshrafSharf** [comment]
Fixed. Please check

**Comment by amanda-phet** [comment]
Perfect! Thanks.
