### ISSUE TITLE
PaperNumberModel's getBounds()

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/making-tens#183]
The equivalent Scenery getBounds() for a view node would include its position, so it's a bit confusing how it is currently named.

Since the function is returning something from PAPER_NUMBER_DIMENSIONS (see https://github.com/phetsims/making-tens/issues/142), presumably it would be getSize() or getDimensions()?

**Comment by AshrafSharf** [comment]
Changed as Suggested. Fixed along with #142
