### ISSUE TITLE
Adjust font size on Adding screen

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/making-tens#19]
It appears that the font size for the numbers is much smaller than the "+" and "=". 
<img width="260" alt="screen shot 2015-07-09 at 4 38 49 pm" src="https://cloud.githubusercontent.com/assets/7852916/8608616/b1e6b352-2659-11e5-977d-ddfff9675dfb.png">

I assume this is so that any number can comfortably fit in the equation. However, the "=" was specified in the design doc to have a variable placement depending on the second number in the equation. So, let's go ahead and reduce the font size of the "+" and "=" to match the numbers and implement some logic so that the equal sign is always appropriately spaced to the right of the right number. 

If it is difficult to place the "=" at startup, before a number is entered, I think it would be fine to wait until the second number is entered for it to show up.

**Comment by amanda-phet** [comment]
@AshrafSharf Does this look like something you can take care of?

**Comment by AshrafSharf** [comment]
The equal sign now appears only after both the terms are entered.
Let me know if this behaviour is fine

**Comment by amanda-phet** [comment]
I think this looks really good. 

Can you adjust the font size of the numbers to match the "+" and "="? The numbers are still much smaller.

**Comment by AshrafSharf** [comment]
Have increased the font size to match the symbols. Let me know if terms are all proportionate in size.
I have given "50" as the font size for symbols and "45" for numbers.

**Comment by amanda-phet** [comment]
They should either both be 50 or both be 45, so that they are the same.

**Comment by amanda-phet** [comment]
Below I have mocked up the different sizes and when the numbers and symbols are different, it looks less proportional. 
![screen shot 2015-08-31 at 11 53 07 am](https://cloud.githubusercontent.com/assets/7852916/9585963/31e2d1c0-4fd7-11e5-80bb-8eecebf8c089.png)

**Comment by AshrafSharf** [comment]
Do you prefer, font size of 45 for both symbols and numbers?

**Comment by amanda-phet** [comment]
I think size 45 is fine- it may help to address #36 if we go with the smaller number. Thanks!

**Comment by AshrafSharf** [comment]
@amanda-phet made font size 45. Please check it

**Comment by amanda-phet** [comment]
Looks great. Closing.
