### ISSUE TITLE
ExpressionTermsNode direction

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/making-tens#192]
it calls ```setDirection( 'rtl' )``` on a Text node. What's the purpose of this?

**Comment by AshrafSharf** [comment]
removing leftTermTextNode.setDirection( 'rtl' ) breaks the terms layout. The Plus character doesn't get placed properly.

Have attached the screenshot. Please advice.
![image](https://cloud.githubusercontent.com/assets/8498160/16066076/fd0a5254-32cd-11e6-8323-f081d3e46eda.png)
