### ISSUE TITLE
ExpressionTermsNode' emptyNode

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/making-tens#193]
What is the purpose of it?:
```js
var emptyNode = new Text( '', { font: EQUATION_FONT, fill: EQUATION_COLOR } );
```

It gets added to the HBox's children, and that's all. If it's used for the equalsSignNode's layout (only thing that SHOULD be affected), please remove emptyNode and add in the HBox's spacing to that offset.

**Comment by AshrafSharf** [comment]
Have removed Empty Node. Visually it didn't make any difference so I am not adding any offset.
