### ISSUE TITLE
ExpressionTermsNode layout

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/making-tens#194]
I see:
```js
    leftTermProperty.link( function( leftTerm ) {
      leftTermTextNode.text = leftTerm;
      updateEqualSpacing();
    } );
```
but it seems the equals sign's layout is only dependent on the right term's length, so this is unnecessary?

Also in updateEqualSpacing(), the equals sign is centered vertically. Presumably this can be done just once up-front?

Also:
```js
leftTermTextNode.centerY = numberDisplayBox.top + numberDisplayBox.height / 2;
// ...
rightTermTextNode.centerY = numberDisplayBox.top + numberDisplayBox.height / 2;
```
is equivalent to:
```js
leftTermTextNode.centerY = numberDisplayBox.centerY;
// ...
rightTermTextNode.centerY = numberDisplayBox.centerY;
```

**Comment by jonathanolson** [comment]
Additionally, the plus and equals sign seem to have differing layouts:
```js
equalsSignNode.centerY = numberDisplayBox.top + numberDisplayBox.height / 1.9;
```

Ideally, they should have the same centerY, so that they are visually vertically aligned.

**Comment by AshrafSharf** [comment]
All suggestions in this issue are implemented.
updateEqualSpacing() is triggered only on right term's length. The vertical positioning is taken out of the updateEqualSpacing and done only once.
Vertical Positioning of termNodes are also done the way as recommended
