### ISSUE TITLE
ExpressionTermsNode options

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/making-tens#195]
I was about to say "leftTermBackgroundStyleProperty and rightTermBackgroundStyleProperty don't seem to be used anywhere, so presumably that code is unneeded?", but then I noticed that the entire adding model is getting passed in (!) as the options object.

In general, that is a bad pattern to follow, has it's really difficult to track down how things are working.

In this particular case, I'd recommend that ExpressionTermsNode have properties (possibly optional) passed in, that determine when the left and right terms should be "active". Whether they are active should JUST toggle their visibility. ```new Property( false )``` could be the default, since this is what is equivalently used in the game screen.

This is preferred, as right now the fills on the backgrounds are ignored (overwritten with null OR invisible), the stroke changes between black and null (visibility should be used instead), and the lineDash changes (very unnecessary).

See https://github.com/phetsims/making-tens/issues/55

**Comment by jonathanolson** [comment]
This also means "showTermBackground" would be removed.

Additionally, I'd recommend that the 'backgrounds' potentially be renamed as 'borders' or 'highlightBorders', since they never have a visible fill.

**Comment by jonathanolson** [comment]
Also, it appears that activeTermProperty is being grabbed from the model. This should be explicitly passed in if needed.

**Comment by AshrafSharf** [comment]
Style objects are moved to View
A new ExpressionTerms model is used which is now passed to ExpressionTermsNode. (The ExpressionTerms Model has behaviour to check emptiness)
The showBackground is changed to hightlightBorders
