### ISSUE TITLE
ExpressionTermsNode isEmpty usage and MakingTensAddingModel terms

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/making-tens#196]
It looks like it is being used for the leftTerm and rightTerm in the adding model (only when activeTermProperty exists currently, see https://github.com/phetsims/making-tens/issues/195).

It seems to me the left/right terms should either be null/0 or an integer 1+, so isEmpty shouldn't be used (and empty strings shouldn't either).

Can the MakingTensAddingScreenView pass through a property of when the equals sign should be visible, and there it can check all the cases needed?

**Comment by AshrafSharf** [comment]
IsEmpty check is removed. The term checking behaviour is abstracted into a separate method.
The code is refactored as part of #195
