### ISSUE TITLE
Naming of paper numbers between model and view

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/making-tens#198]
Why does the model use 'residentNumberModels' but the view uses 'paperNumberNodes'?

Seems more consistent if the model used 'paperNumbers' and the view used 'paperNumberNodes'.

**Comment by jonathanolson** [comment]
Wait, it seems paperNumberNodes is completely unused (could potentially be removed).

**Comment by jonathanolson** [comment]
Actually, it seems it SHOULD be used in MakingTensCommonView instead of:
```js
var allPaperNumberNodes = this.paperNumberLayerNode.children;
```

Please push and remove children from paperNumberNodes as necessary, in addition to maintaining the map described in https://github.com/phetsims/making-tens/issues/199.

**Comment by AshrafSharf** [comment]
Changes implemented as suggested
