### ISSUE TITLE
MakingTensCommonView's findPaperNumberNode

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/making-tens#199]
There's a general preferred pattern to look up view objects that correspond to model objects:
1. Put a unique numeric (incrementing) ID on every PaperNumberModel, e.g. ```this.id = someGlobalId++;```
2. Create an object ('paperNumberNodeMap'?) in the view where the keys are the model IDs and the values are the nodes, e.g. ```this.paperNumberNodeMap[ paperNumber.id ] = paperNumberNode```.
3. When the look up is needed, it is just ```this.paperNumberNodeMap[ paperNumber.id ]```.

I'd recommend this pattern be used here.

**Comment by AshrafSharf** [comment]
Changes implemented as suggested.
