### ISSUE TITLE
Decrease bounce-back distance between numbers that can not be combined 

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/making-tens#20]
If you try to put the 2 on top of the 9, the 2 "bounces" a specified distance off to the left.
<img width="936" alt="screen shot 2015-07-09 at 4 47 41 pm" src="https://cloud.githubusercontent.com/assets/7852916/8608671/5275c89e-265a-11e5-975f-79c6bb5c674a.png">

In the 7/9 design meeting we determined that the distance seems slightly more reasonable for the 100s and 10s than the 1s. In order for it all to look reasonable, we would like to use a "repelling" behavior instead of "bouncing-away." When two numbers are combined, such as 2 and 9, regardless of which number was placed on top of the other, they two numbers will repel and move equally to the right and left so that the distance between them is like this: 
<img width="935" alt="screen shot 2015-07-09 at 4 51 18 pm" src="https://cloud.githubusercontent.com/assets/7852916/8608704/c1cfdca2-265a-11e5-8a06-f4fb70e21b2c.png">
The same repelling behavior will occur any two numbers, regardless of size, if the user attempts to combine them incorrectly (e.g., 40 and 70).

**Comment by AshrafSharf** [comment]
Fixed. when the numbers are close to  right or left edges only one of then gets bounced away otherwise they repel each other, if they cannot be combined.

**Comment by amanda-phet** [comment]
The repelling looks really nice! Closing.
