### ISSUE TITLE
Multiple buttons with same content

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/making-tens#203]
It's not recommended to have multiple buttons with the same content, e.g. MakingTensAddingScreenView's createEditNumberButton uses the same scaledIcon.

This is because each button is responsible for the content's positioning. If the buttons are ever changed to not be identical in the future, it would be a visually noticeable bug in the position of the content in one of the buttons.

I'd recommend using createSizedImageNode inside the createEditNumberButton so it is called twice (and optionally, inline the entire scaledIcon variable).

**Comment by AshrafSharf** [comment]
Done as suggested.
