### ISSUE TITLE
MakingTensAddingScreenView's onNumberSubmit

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/making-tens#204]
Due to the recommended casting in https://github.com/phetsims/making-tens/issues/145, this function would presumably pass through zeros OR convert zeros to null (see https://github.com/phetsims/making-tens/issues/58). I'm fine with either of those choices.

**Comment by AshrafSharf** [comment]
The NumberKeyPad which is from Scenery Phet uses string to display digits. So only when value is set to NumberKeyPad it is translated to and from string. In all other places it is either null or a  number.
