### ISSUE TITLE
MakingTensCommonModel addUserCreatedNumberModel

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/making-tens#207]
Why is the 'user created' part relevant?

Also, this function is being used in MakingTensExploreScreenView to split the number into parts as it is put back in the panel. I wouldn't call those "user created".

**Comment by jonathanolson** [comment]
I'd recommend a naming that is symmetric:
- addPaperNumber
- removePaperNumber

**Comment by AshrafSharf** [comment]
methods renamed as recommended
