### ISSUE TITLE
Use custom cursors on different areas 

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/making-tens#21]
On the bottom two-thirds of a number (the region that is dedicated to dragging) we would like to use the "move" cursor shown here: http://phetsims.github.io/scenery/examples/cursors.html. Whenever the cursor hovers over this region, it will change into the move cursor.

<img width="142" alt="screen shot 2015-07-10 at 9 09 52 am" src="https://cloud.githubusercontent.com/assets/7852916/8621555/77162c6e-26e3-11e5-8ef4-2218a702312c.png">

On the top third (the region that is dedicated to pulling off a 1) we would like to use the "pointer" cursor. Whenever the cursor hovers over this region, it will change into the pointer.
<img width="132" alt="screen shot 2015-07-10 at 9 14 33 am" src="https://cloud.githubusercontent.com/assets/7852916/8621673/2fd1a18e-26e4-11e5-8df9-77f69591cb3c.png">

**Comment by samreid** [comment]
What is the plan for user interaction on touch devices with no mouse, such as iPad?

**Comment by amanda-phet** [comment]
We are planning to see how students use the sim on an iPad in interviews. If the interaction is confusing we will use a different type of feedback that helps a touch user with the "rules" for interaction.

**Comment by AshrafSharf** [comment]
Done.

**Comment by amanda-phet** [comment]
This looks great. Thanks!
