### ISSUE TITLE
PaperNumberModel's determineDigitIndex

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/making-tens#218]
It has a map from basePositions to positionBuckets (potentially as a way of hoping to increase performance).

The function closure will actually decrease performance more than accessing '.x' twice would be, so I'd recommend just using ```basePositions[ i ].x``` instead of ```positionBuckets[ i ]```.

**Comment by AshrafSharf** [comment]
basePositions is an object hash, thats why it is converted into an array of x values

**Comment by jonathanolson** [comment]
I understand that it may be easier to read, however the function closure will tend to cause garbage collection issues. I believe this should be changed.
