### ISSUE TITLE
Place value when making a ten should be consistent

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/making-tens#22]
When I make a ten (by combining a 1 and 9, for example), the *1* in the *10* replaces the 9.

![make10](https://cloud.githubusercontent.com/assets/7852916/8622136/0403441a-26e7-11e5-9205-3e6f55d4fa3a.gif)

We would like to keep the place value consistent, so instead, the *0* in the *10* should replace the 9. 

The same should be true when making a hundred. All place values should align.

**Comment by AshrafSharf** [comment]
issue fixed.

**Comment by amanda-phet** [comment]
This is working really well with 10- when I make a 10 or take apart a 10, the place value is consistent. 

However, when breaking apart 100, the 1 in the 10 still replaces the ones place in the 100. I think it should have the same consistency as the 10, or when making 100.

**Comment by AshrafSharf** [comment]
The old 3 digit paper images had a disproportionate size. I have now replaced the old images with the new ones. I have also made code changes to make sure three digits number pull and combine placement is consistent. The Height difference between 3 and 2 digit numbers are more than between 2 and single digit numbers. Let me know if this is consistent.

**Comment by bethstade** [comment]
Better, but there is still some jumping when numbers are added. When 9 and 1 make ten, and 10 and 90 make 100, the ones place DIGIT should remain in the exact position. That is, the alignment should be with the digits, not the paper.  Right now if I add 10 and 90,  then add, then take apart again, then add, the digits and paper drift downward.

**Comment by AshrafSharf** [comment]
Fixed.

**Comment by amanda-phet** [comment]
It looks perfect to me!
