### ISSUE TITLE
PaperNumberCreatorNode's droppedScreenPoint

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/making-tens#220]
It is created with:
```js
var droppedScreenPoint = parentScreenView.globalToLocalPoint( event.pointer.point );
```
and thus isn't in the screen/global coordinate frame, but the view coordinate frame. It would be best to be named droppedViewPoint/viewPoint or an equivalent.

**Comment by AshrafSharf** [comment]
Variable name refactored to droppedViewPoint
