### ISSUE TITLE
copy of vegas.LevelSelectionButton

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/making-tens#226]
making-tens.LevelSelectionButton, line 6:

```js
 * The Vegas LevelSelectionButton is copied over to MakingTens, because of the need to display
 * the score in "Text", next  to the star symbol.
```

Do not copy common-code components. Open an issue to add functionality needed to those components.

**Comment by jonathanolson** [comment]
Duplicate of https://github.com/phetsims/making-tens/issues/81
