### ISSUE TITLE
White boxes covering numbers on game screen challenges

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/making-tens#23]
For some reason, on the Game screen, (perhaps after fixing #8?) there are white boxes with outlines where there should be numbers. 
![screen shot 2015-07-13 at 12 21 43 pm](https://cloud.githubusercontent.com/assets/7852916/8657279/e14a8670-2959-11e5-92f1-f0b08e5518da.png)

**Comment by AshrafSharf** [comment]
Fixed

**Comment by amanda-phet** [comment]
Looks fixed. Closing.
