### ISSUE TITLE
The images for the number paper cut-outs are very gray

### ISSUE THREAD

**Issue by samreid** [phetsims/making-tens#24]
I saw this screenshot in another issue:

![image](https://cloud.githubusercontent.com/assets/679486/8664126/dd87d53e-298f-11e5-982f-efecbc924b03.png)

The paper cut-outs are such a dark gray that they look somewhat dirty, especially when there is any other white on the screen (not necessarily within the sim).  I have been out of the loop for the artwork for this sim, but just wondering why it is so dark, and thought that maybe brightening it a lot would help it look more like paper.

**Comment by bethstade** [comment]
This is not the final artwork - justs clips from SnowDay.
Final version will be whiter and brighter.

----- Original Message -----From: Sam Reid <notifications@github.com>To: phetsims/making-tens <making-tens@noreply.github.com>Sent: Tue, 14 Jul 2015 00:51:01 -0000 (UTC)Subject: [making-tens] The images for the number paper cut-outs are very gray (#24)

I saw this screenshot in another issue:

The paper cut-outs are such a dark gray that they look somewhat dirty, especially when there is any other white on the screen (not necessarily within the sim). I have been out of the loop for the artwork for this sim, but just wondering why it is so dark, and thought that maybe brightening it a lot would help it look more like paper.
&mdash;Reply to this email directly or view it on GitHub.

**Comment by amanda-phet** [comment]
@samreid Beth is correct. Thanks for the suggestion!
