### ISSUE TITLE
Snow Day Math image licensing

### ISSUE THREAD

**Issue by samreid** [phetsims/making-tens#25]
I added an exception to classifyLicenseForFile that will permit the build to succeed.  When the number/paper images are replaced, please contact @samreid so that I can remove the exception.

**Comment by samreid** [comment]
The exception is noted in the commit above.

**Comment by pixelzoom** [comment]
Recommendations:

1. Instead of putting sim-specific code in grunt tasks, put dummy data in license.json, to encapsulate the workaround where it needs to be encapsulated.  Here's why: The description says "I added an exception to classifyLicenseForFile".  But you also added an exception to getLicenseInfo.js that isn't indicated anywhere. 

2. Rename making-tens repository to snow-day-math.

**Comment by pixelzoom** [comment]
Reassigning this to @samreid, since I believe the first step should be to relocate the workaround from code to license.json.

**Comment by samreid** [comment]
I moved this exception from "logic in chipper" to "projectURL annotations in making-tens/images/license.json".  Tested a build and everything worked nicely.  I'll commit shortly.

I wasn't sure why @pixelzoom recommended the following, can you provide context?
> Rename making-tens repository to snow-day-math.

@pixelzoom anything else to do here for now?

**Comment by pixelzoom** [comment]
I suggested renaming the repo to snow-day-math because I thought that "Snow Day Math" was the new title of the sim.

**Comment by pixelzoom** [comment]
Consider using the approach described in https://github.com/phetsims/john-travoltage/issues/82#issuecomment-127682789 to handle the images herein.

**Comment by samreid** [comment]
I used the "exception" approach from John Travoltage and tested grunt with and without a missing exception.  Looks good.  @pixelzoom anything else

**Comment by samreid** [comment]
Accidentally closed, still wondering if there's anything else to do here.

**Comment by pixelzoom** [comment]
:+1: Closing.

During a build, I don't see any warning message for media files that have "exception". But we can discuss that in https://github.com/phetsims/chipper/issues/222.
