### ISSUE TITLE
Explore screen panel behavior

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/making-tens#3]
In the explore screen of Making Tens, users can pull out 1, 10, or 100 from the panel on the bottom of the screen. 
![screen shot 2015-06-25 at 3 24 04 pm](https://cloud.githubusercontent.com/assets/7852916/8365984/45e43d66-1b4e-11e5-9551-3a433c04594f.png)

We usually also allow users to return an item to a panel (see the Balance Lab screen: https://phet.colorado.edu/sims/html/balancing-act/latest/balancing-act_en.html). 

Can you incorporate this behavior? If a 1, 10, or 100 gets close enough to the panel (maybe more than 60% of the paper is overlapping the panel), it should be returned to the panel.

**Comment by AshrafSharf** [comment]
Have included the Paper Number returning to the Panel. Let me know if this behaviour of fine.

(Though not related, I have also fixed some number rules with regard to 2 digits)

**Comment by amanda-phet** [comment]
I pulled the latest version but am not seeing this behavior. In the screenshot below, the 10 should be returning to the panel.
![screen shot 2015-06-30 at 3 10 46 pm](https://cloud.githubusercontent.com/assets/7852916/8442155/4066989e-1f3a-11e5-980e-89745faf6559.png)

**Comment by AshrafSharf** [comment]
Have checked it in Safari. I used a string method "startsWith" which is still not available on Chrome. I have replaced this that method with custom logic.
Now the explore panel is working as expected on Safari

**Comment by amanda-phet** [comment]
Safari was not the issue here. I used Firefox, and just checked Chrome and Safari, and the numbers do not return to the panel in any of these browsers. I am running Mac OS 10.10.

**Comment by amanda-phet** [comment]
We will discuss the ideal behavior for how the pieces should return to the panel before @AshrafSharf continues to work on this.

**Comment by amanda-phet** [comment]
We decided that the components of a number should split up and return to the appropriate pile. For example, when the number 365 returns to the dock, 300 would animate over to the 100s pile, 60 would animate over to the 10s pile, and 5 would animate over to the 1s pile. 

When the number component is over the appropriate pile, it will essentially disappear.

**Comment by AshrafSharf** [comment]
Have fixed it.

**Comment by amanda-phet** [comment]
It looks really good to me. It's too fast to notice the detail of the numbers splitting up, but it's obvious what is happening. I'd like other team members to look at it and see what they think @bethstade @ariel-phet . 

The only thing I might want to change is how far to the right of the 1s pile the units seem to be flying.

**Comment by bethstade** [comment]
I like the action of the numbers going back.  In particular I like that the number needs to be quite deep in the box to trigger the return to the piles. I am fine with all the action.
I did notice an odd bug.  
So if I make 121 and return it, it all works.
However, if I make 121, then split it into 100, 20, and 1, I can return the 100, but not the 20 or 1.  Seems consistent that I can't return the lower digits if they have been part of a larger number and then removed.  The screen shot is just the 20 NOT return to the dock.
<img width="934" alt="screen shot 2015-08-04 at 1 07 17 pm" src="https://cloud.githubusercontent.com/assets/5370001/9070149/0a010ad2-3aab-11e5-9ba7-d304e855a64e.png">

**Comment by amanda-phet** [comment]
You're right @bethstade that is a bug! I'll make a separate issue for that bug. I'll keep this one open to continue the discussion about how this feature is looking. The only thing I don't like is how far to the right the units digit seems to fly. If I return a single 9, it disappears above the 1's and looks normal. But if I return 109, the 9 disappears outside of the panel. It is odd to me that they disappear at different locations.

**Comment by bethstade** [comment]
I agree. The ones from a 3 digit numbers are flying off too far to the right.  They should fly to the pile as they do from single and double digit numbers

**Comment by AshrafSharf** [comment]
Numbers of different digit lengths are now properly returning to its collection.

**Comment by amanda-phet** [comment]
It looks great to me. Thanks!
