### ISSUE TITLE
Single digits "snap in place" boundary

### ISSUE THREAD

**Issue by bethstade** [phetsims/making-tens#33]
When putting a single digit piece ONTO a larger piece there is a difference when we approach the zero from the left or right.  From the right, the single digit will snap in place when near the zero and this consistent with other snapping behavior and is correct.  However, if the single digit comes in from the LEFT, there is no threshold that snaps the digit in place and the single digit must be placed EXACTLY.  We need this behavior on the left to act like the same as the right.

**Comment by AshrafSharf** [comment]
Have Fixed it

**Comment by amanda-phet** [comment]
Can you make the behavior the same for bot the left and right? 

For example, this is as close as I can get *from the left* before the numbers combine:
![screen shot 2015-08-14 at 2 13 14 pm](https://cloud.githubusercontent.com/assets/7852916/9283148/b42bc480-428e-11e5-8677-92a6620c920a.png)

And this is how close I can get *from the right*: 
![screen shot 2015-08-14 at 2 13 42 pm](https://cloud.githubusercontent.com/assets/7852916/9283146/b171d19e-428e-11e5-8d52-7443a75fc638.png)

It seems like they should behave consistently coming from either side.

**Comment by AshrafSharf** [comment]
Have Fixed It. Please Check

**Comment by amanda-phet** [comment]
It looks great to me! Closing.
