### ISSUE TITLE
change request list

### ISSUE THREAD

**Issue by bethstade** [phetsims/making-tens#35]
Beth 's list for thought
1. address area under box in explore screen.
2. where is the boundary on the numbers.
3. do we need more clues for pulling off.
4. limit 20000. when 20,000 is total - leave just one of each paper below. limit 20,111.

**Comment by amanda-phet** [comment]
Elaboration on above items during 9/1 discussion: 

1. If a number is dropped in the area under the blue panel, it is considered returned to the panel. The "return zone" for the blue panel extends to the area below the blue panel.
2.  The touch area for pulling off a number is supposed to be the top two thirds of the number. Right now it seems like this touch area is the top fifth. 
3. When we do interviews, we will see how students interpret the interaction, then revisit cues for where to touch for moving or pulling off.
4. The limit will be 9,999 instead of 20,000 so that we do not need to design an even larger number piece. The piles are infinite until the total reaches a certain threshold. Then the piles are reduced to one piece of paper, then none when 9,999 is reached.

**Comment by amanda-phet** [comment]
After discussing with @jonathanolson , it sounds like the logic for addressing 4 above (limiting the sum to 9,999) is not too difficult to implement, but the feedback of seeing just one piece of paper is tricky. Consider the case where the user is at a sum of 9,890. It is possible to pull out another 100. But if they pull out 10, 100 is no longer possible. If the single piece left in the panel simply disappears, that is unexpected and have an undesirable effect on a user, but if it simply changes appearance to look inactive it won't feel unexpected. 

@ariel-phet I think interviews are going to be necessary before we address 2 and 3 above. 

I would like to add another change request, as well.

5. When a piece is pulled out of the panel, the cursor should be closer to the bottom of the paper. It is possible right now to be holding the paper by the top, in the region where we pull off numbers, and that shouldn't be possible.

**Comment by ariel-phet** [comment]
@amanda-phet - I think you should definitely address 2 above...we should first take our best guess at what feels right before interviews...also I don't think the touch area matches the spec, is that correct?

**Comment by amanda-phet** [comment]
@ariel-phet you're correct that the touch area doesn't match the spec, but I'm not sure that our original design is the best choice either. But I'm fine making that change before interviews.

**Comment by ariel-phet** [comment]
@amanda-phet - I think before interviews we should go with what you and your instincts think will work best in terms of the touch area.

**Comment by bethstade** [comment]
I had my class try out Making Tens today.  I had them play and do activities in groups for about 45 minutes.  They suggested that the "upper 3nd" or quarter was the right area for "pulling off." In general the class felt that it was natural to move the number from the middle and if the divide was in the middle, then they would always be messing up. The touch screen on the iPhone worked great!  They felt the pad experience was better than the computer.

**Comment by bethstade** [comment]
I am offering extra credit for them to to test and do projects with it.

**Comment by bethstade** [comment]
And yes, dog ears might be good in the explore screen - you know it pains  me to say so.

**Comment by amanda-phet** [comment]
Did you allow them to play with the sim without any introduction from you? Or did you explain how to use the sim first?

**Comment by bethstade** [comment]
No explanation at all.  Just asked them to try explore screen first.  It took a bit to find out that the numbers cam apart.

**Comment by amanda-phet** [comment]
Based on @bethstade 's experience with her class, should we stick with the current 1/3 and 2/3 touch areas?

**Comment by bethstade** [comment]
I think the actual area seems more like 1/4 and 3/4 althought we said 1/3 and 2/3.
I am making arrangements to test Making test with BVSD teachers.
I am pretty sure I can test it out with a 1st, 4th, and 6th grade classes in the next come weeks.
I take some video and see if the reactions are the same across the grades fro ease of touch and just "figuring it out could."
Might make sense to look at that before making change requests.

----- Original Message -----From: Amanda McGarry <notifications@github.com>To: phetsims/making-tens <making-tens@noreply.github.com>Cc: bethstade <stadee@colorado.edu>Sent: Thu, 10 Sep 2015 17:18:00 -0000 (UTC)Subject: Re: [making-tens] change request list (#35)

Based on @bethstade 's experience with her class, should we stick with the current 1/3 and 2/3 touch areas?
&mdash;Reply to this email directly or view it on GitHub.

**Comment by amanda-phet** [comment]
I measured the distance and it is 1/3... I thought it was 1/4 too but the ragged/slanted paper edge makes it seem much smaller. We can always change it though, to whatever we think feels right! 

Let's talk today about your student testing. It may be possible to use your data as more than informal anecdotes!

**Comment by bethstade** [comment]
yes. Let's talk about what can be useful.

----- Original Message -----From: Amanda McGarry <notifications@github.com>To: phetsims/making-tens <making-tens@noreply.github.com>Cc: bethstade <stadee@colorado.edu>Sent: Thu, 10 Sep 2015 18:25:08 -0000 (UTC)Subject: Re: [making-tens] change request list (#35)

I measured the distance and it is 1/3... I thought it was 1/4 too but the ragged/slanted paper edge makes it seem much smaller. We can always change it though, to whatever we think feels right!
Let's talk today about your student testing. It may be possible to use your data as more than informal anecdotes!
&mdash;Reply to this email directly or view it on GitHub.

**Comment by amanda-phet** [comment]
I opened #40 as the official request for Ashraf, so I'll close this issue.
