### ISSUE TITLE
Numbers on adding screen don't fit in boxes

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/making-tens#36]
This may be because of the changes made in #19 but the numbers don't fit in the boxes very well. 

![screen shot 2015-08-31 at 11 49 55 am](https://cloud.githubusercontent.com/assets/7852916/9586011/83456492-4fd7-11e5-8152-b3e475dcff1f.png)

![screen shot 2015-08-31 at 11 50 06 am](https://cloud.githubusercontent.com/assets/7852916/9586016/878bb2a4-4fd7-11e5-8cc0-4b25fdbb4f96.png)

**Comment by AshrafSharf** [comment]
can the highlight box be of constant size as shown below, or should this be based on the no of digits?

Single Digit
![image](https://cloud.githubusercontent.com/assets/8498160/9586418/660befdc-503a-11e5-9276-29ac2fafc23a.png)

Two Digit
![image](https://cloud.githubusercontent.com/assets/8498160/9586430/83505df8-503a-11e5-9e50-3e205900c179.png)

three digits
![image](https://cloud.githubusercontent.com/assets/8498160/9586450/9bf4f634-503a-11e5-91cd-33f2e083af86.png)

**Comment by bethstade** [comment]
I think constant.

----- Original Message -----From: Ashraf <notifications@github.com>To: phetsims/making-tens <making-tens@noreply.github.com>Sent: Mon, 31 Aug 2015 18:18:34 -0000 (UTC)Subject: Re: [making-tens] Numbers on adding screen don't fit in boxes (#36)

can the highlight box be of constant size as shown below, or should this be based on the no of digits?
Single Digit
Two Digit
three digits
&mdash;Reply to this email directly or view it on GitHub.

**Comment by amanda-phet** [comment]
I think constant is good, especially since the buttons are aligned with the highlight boxes.

**Comment by AshrafSharf** [comment]
Fixed. Please Check it

**Comment by amanda-phet** [comment]
This looks great to me!
