### ISSUE TITLE
Touch area bug

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/making-tens#37]
When playing around with the sim while ?showPointerAreas was on, I noticed a bug. When I break apart a number, say 100 into 90 and 10, the touch area for 90 is as large as it was for 100. When I modify the 90 by continuing to break apart and add numbers, the touch area remains as it was for 100. Notice the same thing happened when breaking apart 10 into 9 and 1. 
![screen shot 2015-09-10 at 11 18 09 am](https://cloud.githubusercontent.com/assets/7852916/9795431/da998aa6-57ad-11e5-972d-6ceb2a608d7d.png)

I confirmed without the query parameter that I can move a number by clicking way outside of the paper. We just hadn't noticed this before!

**Comment by AshrafSharf** [comment]
This was introduced when I explicitly assigned mouse and toucharea to fix issue #16.
Now the touch and mouse are gets updated when ever the number value changes.

**Comment by ariel-phet** [comment]
@amanda-phet - it would be good to verify this fix next time you are on campus

**Comment by amanda-phet** [comment]
I'm having a hard time opening the sim. I pulled the latest version just now (although it said it was already up-to-date) and I'm just getting a blank screen.

**Comment by ariel-phet** [comment]
@amanda-phet - you probably need to pull all the repos, there have been lots of other things changing, I will see if I can test it tonight

**Comment by ariel-phet** [comment]
Appears fixed in latest dev version

http://www.colorado.edu/physics/phet/dev/html/making-tens/1.0.0-dev.4/making-tens_en.html?showPointerAreas

Closing
