### ISSUE TITLE
Cursor placement when taking a number out of the panel

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/making-tens#41]
When a number piece is pulled out of the panel on the Explore screen, the cursor should within the bottom-third touch area (the region intended for moving numbers). This means the number piece may jump up a bit when clicked in the panel, and that is OK.
![screen shot 2015-09-23 at 10 31 25 am](https://cloud.githubusercontent.com/assets/7852916/10051371/5bad8f9a-61de-11e5-8977-106b09524aeb.png)
![screen shot 2015-09-23 at 10 31 34 am](https://cloud.githubusercontent.com/assets/7852916/10051375/5e5d0342-61de-11e5-8c38-00931585a078.png)

**Comment by AshrafSharf** [comment]
Implemented the behaviour but also changed the code to show "pointer" cursor only when the user hovers over the bottom portion of the node. Let me know if this cursor behaviour is fine.

**Comment by jonathanolson** [comment]
Clarification for the record:

Pressing the mouse down on any location on a number in the panel should start a drag. When this happens, the number should be visually shifted up (if necessary) so that the mouse cursor is well within the "drag this number" bounds.

**Comment by AshrafSharf** [comment]
After having a discussion with @jonathanolson  got some more details on this issues. Have fixed it. Please verify

**Comment by amanda-phet** [comment]
Looks really good. Thanks @AshrafSharf !
