### ISSUE TITLE
Change maximum total to 9,999

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/making-tens#42]
The maximum total that a user can build is currently 1,998 (999+999). This works well on the Addition screen, but not on the Explore screen. Therefore, we need a more reasonably high maximum of 9,999. This means that a user can pull out any piece as long as it does not bring the total above 9,999. If a number piece could bring the total above 9,999, it will appear disabled. 
![screen shot 2015-09-23 at 10 22 01 am](https://cloud.githubusercontent.com/assets/7852916/10051086/fcec23d2-61dc-11e5-9038-635a63291e49.png)

I will email you the artwork for 2000-9000 since those do not currently exist.

**Comment by bethstade** [comment]
Just to clarify logic for larger numbers.
 A number such as 3456 should pull apart from right to left:
3450  and 6   (pull from far right)
3400 and 56  (pull from middle right)
3000 and 456 (pull from middle left)
1000 and 2456 (pull from far left)

3400 gives you 
1000 and 2400 pulled (from far left)
3000 and 400 (pulled from ANYWHERE else)

3000 gives you 
2000 and 1000 pulled from anywhere.

1000 gives you 900 and 100 pulled from anywhere.

**Comment by AshrafSharf** [comment]
Added support for numbers larger than 1000.
Tested the above rules, they are working fine.
Please verify it.

**Comment by bethstade** [comment]
Close.
From 3450, if I pull from the middle right (above the 5) I get the 50, which is correct.
BUT if I pull from the far right (above the 0) I get 450.
I should get 50 coming off from anywhere over 50.
Thanks.

**Comment by amanda-phet** [comment]
@bethstade I made 3,450 and noticed what you are pointing out as well. In general, the top piece of paper should be removed if the cursor is anywhere above that piece of paper (in this case the top would be 50).

**Comment by amanda-phet** [comment]
This seems to be working to me, but @bethstade you know the rules so intimately- can you confirm that it is fixed and then close the issue?

**Comment by bethstade** [comment]
Thanks.
I will check it out on Monday.

----- Original Message -----From: Amanda McGarry <notifications@github.com>To: phetsims/making-tens <making-tens@noreply.github.com>Cc: bethstade <stadee@colorado.edu>Sent: Fri, 23 Oct 2015 23:02:52 -0000 (UTC)Subject: Re: [making-tens] Change maximum total to 9,999 (#42)

Assigned #42 to @bethstade.
&mdash;Reply to this email directly or view it on GitHub.

**Comment by bethstade** [comment]
Looks great.
