### ISSUE TITLE
Expand "return zone" for numbers returning to the panel

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/making-tens#43]
If a number is dropped in the area under the blue panel (on the Explore scree), it is considered returned to the panel. The "return zone" for the blue panel should extend to the area below the blue panel. 
![screen shot 2015-09-23 at 10 05 38 am](https://cloud.githubusercontent.com/assets/7852916/10050650/aede6e2c-61da-11e5-9ecb-9716d65f8507.png)

**Comment by AshrafSharf** [comment]
Fixed. Please verify.

**Comment by bethstade** [comment]
Looks good.

**Comment by amanda-phet** [comment]
#44 seems to have helped with this and is working for the most part. However, I noticed that if I click on a number and do not drag it anywhere, it gets "stuck" in a region where it should be returned to the panel. 
<img width="593" alt="screen shot 2015-10-21 at 12 39 43 pm" src="https://cloud.githubusercontent.com/assets/7852916/10646550/d731b93e-77f0-11e5-97ef-7cf91681022b.png">

Perhaps after addressing #41 this will be solidly fixed, but for now we should keep it open.

**Comment by AshrafSharf** [comment]
After having a discussion with @jonathanolson  got some more details on this issues. Have fixed it. Please verify

**Comment by amanda-phet** [comment]
Looks great!
