### ISSUE TITLE
Adjust boundary for play area

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/making-tens#44]
A consequence of #43  is that the boundary for the play area must be adjusted. A piece of paper should not be able to be hidden below the *bottom* of the play area. 
![screen shot 2015-09-23 at 10 25 58 am](https://cloud.githubusercontent.com/assets/7852916/10051174/8465ad2e-61dd-11e5-8aa3-f3826e9edac7.png)
![screen shot 2015-09-23 at 10 26 53 am](https://cloud.githubusercontent.com/assets/7852916/10051196/a378d132-61dd-11e5-9649-3f54e20d6d38.png)

**Comment by AshrafSharf** [comment]
Fixed it. Please verify

**Comment by bethstade** [comment]
Looks Good. Amanda is back in a couple days and will look to.

**Comment by amanda-phet** [comment]
We wanted only the *bottom* boundary to be adjusted but it seems like all four boundaries were adjusted. Sorry if that was unclear. 

![screen shot 2015-10-21 at 12 53 19 pm](https://cloud.githubusercontent.com/assets/7852916/10646867/d71c4976-77f2-11e5-8854-be9c64db7f4e.png)


@bethstade Can you confirm that this is the correct boundary? Or are you OK with all four boundaries being adjusted?

**Comment by amanda-phet** [comment]
Discussed with @bethstade and @ariel-phet and the above mockup is what the boundary should look like. The numbers should behave as they did before this change request with the exception of numbers at the bottom edge of the viewing port. Numbers should not be allowed below the bottom edge.

**Comment by AshrafSharf** [comment]
Fixed It. Please verify

**Comment by amanda-phet** [comment]
This looks great. Closing.
