### ISSUE TITLE
Change the touch boundaries for moving and pulling off numbers 

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/making-tens#45]
We would like to change the touch area for pulling off a number to be the top 2/5 (so a little above the halfway point), and the bottom 3/5 is for moving the piece around. 
<img width="557" alt="screen shot 2015-09-24 at 4 03 50 pm" src="https://cloud.githubusercontent.com/assets/7852916/10088146/df45cc12-62d5-11e5-8af4-472f30f67a45.png">

**Comment by AshrafSharf** [comment]
Changed the touched boundary height  percentage.

**Comment by amanda-phet** [comment]
This looks good to me. Closing.
