### ISSUE TITLE
[review] Sim should use the common code implementation of the keypad

### ISSUE THREAD

**Issue by jbphet** [phetsims/making-tens#46]
A common code version of the keypad is now available in scenery-phet, called simply "Keypad.js".  This should be used in the Making Tens simulation instead of the current custom implementation.  I'm assigning this to @AshrafSharf for implementation, and he should contact me if there are features that are needed for Making Tens that are not available in the common code version so that we can work together to implement them.

**Comment by jbphet** [comment]
The name of the keypad has been changed to NumberKeypad.

**Comment by AshrafSharf** [comment]
Have replaced the Keypad.js with NumberKeypad from scenery-phet.

**Comment by jonathanolson** [comment]
Looks great, thanks!
