### ISSUE TITLE
Keypad can be clicked through (doesn't block mouse/touch)

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/making-tens#52]
If you put a number behind it, mousing over the keypad (over the number behind) should not have the mouse cursor change, and the number shouldn't be draggable.

Setting ```{ pickable: true }``` on the background should fix this, as should (presumably) using the common-code keypad as requested in https://github.com/phetsims/making-tens/issues/46.

**Comment by AshrafSharf** [comment]
While Keypad is open, user cannot work on the number models (Made the PaperNumberLayerNode pickable false and toggled it when the keypad is closed

**Comment by jonathanolson** [comment]
This commit changed a lot of behavior, particularly whether the numbers can be manipulated while the keypad is open. Presumably we want to be able to interact with the paper numbers while the keypad is open (@amanda-phet, is that correct?), and the only behavioral change I was recommending was that the background of the keypad couldn't be clicked through.

Presumably, we shouldn't need to toggle the pickability of the paperNumberLayerNode at all (it should always be pickable).

**Comment by amanda-phet** [comment]
>we want to be able to interact with the paper numbers while the keypad is open

@jonathanolson That is correct. However, if the keypad is covering a number, it is simply covered and can't be clicked on. The keypad should feel like it is completely covering that region and can not be clicked through.

**Comment by AshrafSharf** [comment]
KeyPad panel was set to pickable = false, so always the background received the mousedown event and closed the keyboard panel. The code is fixed now. Clicking on the background of Keyboard will not dismiss the keyboard.

**Comment by jonathanolson** [comment]
Thanks!
