### ISSUE TITLE
[review] MakingTensAddingModel reset() override

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/making-tens#57]
It isn't calling the reset() on the supertype, so the PropertySet reset() is never being called.

This would help reset the things are being manually reset (not the clear() on resetNumberModels though), and it wouldn't mask bugs by skipping any reset() code overrides on the supertype.

**Comment by AshrafSharf** [comment]
AddingTensModel now calls supertype's reset. Fixed

**Comment by jonathanolson** [comment]
The properties handled in the PropertySet (leftTerm/rightTerm/activeTerm for the adding model) will all be reset when the PropertySet prototype reset method is called, so the following are unnecessary:
```js
      this.leftTerm = '';
      this.rightTerm = '';
      this.activeTerm = 'none';
```

It's important to keep the following statement though:
```js
this.residentNumberModels.clear();
```

Additionally, the inherit function will handle setting up the subtype's prototype with methods from the supertype. Thus, if A declares f(), and B inherits A but doesn't declare its own f(), the call ```B.prototype.f.call( ... )``` will fall back to A's declaration of f(). Thus since MakingTensCommonModel extends PropertySet, this function on it is not needed:
```js
    reset: function() {
      PropertySet.prototype.reset.call( this );
    }
```
and ```MakingTensCommonModel.prototype.reset.call( this );``` (from MakingTensAddingModel) will still work when it is removed.

It's beneficial to leave ```MakingTensCommonModel.prototype.reset.call( this );```, since if in the future someone decides to add back in the reset() function in MakingTensCommonModel, it will be called (and presumably it will also call the PropertySet reset).
