### ISSUE TITLE
[review] MakingTensAddingModel unnecessary polymorphism

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/making-tens#58]
In createTerms(), code is checking for whether the leftTerm / rightTerm is a number of a string:
```js
numberValue === '' || numberValue === 0
```

Generally leftTerm/rightTerm should only be numbers, OR only be strings (not either), and the type should be annotated where they are initially declared in the constructor call.

**Comment by AshrafSharf** [comment]
replaced the test with the following condition

```javascript```
 numberValue = +numberValue;
        if ( numberValue > 0 ) {...}
````

**Comment by jonathanolson** [comment]
Change looks good, although I'm wondering what advantage there is to having the leftTerm and rightTerm be strings instead of {number | null}, where it is null if there is no left term set. Why checking ```_.isEmpty``` for the terms in ExpressionTermsNode (this could turn into ```!== null```)?

This is also somewhat tricky, as right now the adding model uses strings for leftTerm/rightTerm, but the game model uses numbers.

**Comment by AshrafSharf** [comment]
The NumberKeyPad which is from Scenery Phet uses string to display digits. So only when value is set to NumberKeyPad it is translated to and from string. In all other places it is either null or a number.
