### ISSUE TITLE
[review] ArithmeticRules unnecessary early declaration

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/making-tens#59]
In pullApartNumbers(), amountRemaining is declared near the top:
```js
var amountRemaining = 1;
```

but then not used, and at the end it is overridden before being used:
```js
amountRemaining = numberValue - amountToRemove;
numberPulledPartModel = new NumberPulledApartModel( amountToRemove, amountRemaining );
```

Is it a bug that it isn't being used (is 1 important?), or can that top line be removed?

**Comment by AshrafSharf** [comment]
Yes. The early declaration was redundant. The line has been removed.

**Comment by jonathanolson** [comment]
Thanks!
