### ISSUE TITLE
Numbers should go over 1000

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/making-tens#6]
There should be a 1000 piece of paper so 900 and 100 can be combined. Right now, if I combine these two, they become 900. 

Before:
![screen shot 2015-07-01 at 12 26 06 pm](https://cloud.githubusercontent.com/assets/7852916/8461827/90a0e082-1fec-11e5-8d2c-ecf4206f8072.png)
After:
![screen shot 2015-07-01 at 12 27 48 pm](https://cloud.githubusercontent.com/assets/7852916/8461838/9f5c69d4-1fec-11e5-8d73-a7fba133f379.png)

This is particularly detrimental on the adding and game screens where the sum does not reflect the addition statement. 
![screen shot 2015-07-01 at 12 29 27 pm](https://cloud.githubusercontent.com/assets/7852916/8461872/d91fb91e-1fec-11e5-9c0e-370e6b015c0f.png)

**Comment by amanda-phet** [comment]
@AshrafSharf When will the 1000 piece be added? This is a pretty high priority issue to make all three screens function properly.

**Comment by AshrafSharf** [comment]
Added image for 1000 and written its associated rules.

**Comment by amanda-phet** [comment]
Thanks! It's working great.
