### ISSUE TITLE
[review] MakingTensCommonModel Number() casts

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/making-tens#63]
I see a few non-standard way of casting things to numbers in MakingTensCommonModel:
```js
var droppedNumberValue = Number( droppedPaperNumberModel.numberValue );
var draggedNumberValue = Number( draggedPaperNumberModel.numberValue );
```

Additionally, since PaperNumberModel's numberValue looks cast (already) to a number in the constructor, can you clarify on why this is used?

I'd generally prefer for the numberValue to always be a number itself.

**Comment by AshrafSharf** [comment]
The keyboard control returns number as quoted string, so we have to do it in one single place "createTerms" method of MakingTensAddingModel. In all other places number casting is is redundant and removed as suggested.

**Comment by jonathanolson** [comment]
Additionally, there's a cast in ArithmeticRules:
```js
       * @param {number} pulledIndex // in number 309 if the pulled index is 2, it mean users pulled 9
       * @returns {NumberPulledApartModel | null} // null means no value is pulled ot
       */
      pullApartNumbers: function( numberValue, pulledIndex ) {
        numberValue = Number( numberValue );
```

Since the type documentation notes it's a number, presumably the cast isn't needed?

**Comment by AshrafSharf** [comment]
Number cast removed from Aithmetic rules

**Comment by jonathanolson** [comment]
Thanks!
