### ISSUE TITLE
[review] PaperNumberModel getDigitLength() usage

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/making-tens#65]
It seems like there are a ton of places that could be simplified by using this function (PaperNumberModel's changeNumber, MakingTensCommonModel's repelAway, etc.).

Since it's computed in changeNumber, you could also have a property/field on PaperNumberModel like numberModel.digitLength so it's easy to access.

**Comment by AshrafSharf** [comment]
Have added a property called digitLength, which computes the digitlength whenever numbervalue gets modified.Used the same in all other places

**Comment by jonathanolson** [comment]
Looks good, thanks!
