### ISSUE TITLE
Number transparency 

### ISSUE THREAD

**Issue by bethstade** [phetsims/making-tens#69]
The paper have the right transparency when "locked" over another number - for example on 110 you can see the zero below.  However, the transparency is missing when the 10 just hovers over the 100. (Actually, it seems that the transparency remains when the 10 is pulled off UNTIL it leaves the frame of the 100 - then it becomes solid again).
![screen shot 2015-12-07 at 9 37 46 am](https://cloud.githubusercontent.com/assets/5370001/11632985/76103c5c-9cc6-11e5-8bcb-02146701b1f5.png)
![screen shot 2015-12-07 at 9 39 37 am](https://cloud.githubusercontent.com/assets/5370001/11632987/778968ec-9cc6-11e5-93e5-0e3e5842c507.png)

 The transparency should always be apparent.

**Comment by AshrafSharf** [comment]
When hovering over other numbers, the paper number is made to get some minimum transparency.Please verify and let me know if this is fine.

**Comment by bethstade** [comment]
Looks good.
