### ISSUE TITLE
Numbers jump when removing 100 or 10

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/making-tens#7]
In the case of 17, if I pull off the 10, the 7 will jump up and left of its original position. This puts it behind the 10 that I'm holding, making it impossible to return to the 17 without also dragging the 10 up and left where the 7 is. It is important that the 7 stay in the same place, because as a user is exploring and learning how to use the sim, if they click in the area that removes the 10, we don't want them to be confused, and ideally they could let go of the 10 and return it back to where it was with little or no consequence. 

This also happens with a 3-digit number such as 125. When I pull off 100, the 25 jumps up and left behind the 100.

**Comment by AshrafSharf** [comment]
Issue is Fixed

**Comment by amanda-phet** [comment]
This looks good. Closing.

**Comment by bethstade** [comment]
Thanks Amanda.
Which version should I be looking out now?


----- Original Message -----From: Amanda McGarry <notifications@github.com>To: phetsims/making-tens <making-tens@noreply.github.com>Sent: Mon, 13 Jul 2015 18:25:26 -0000 (UTC)Subject: Re: [making-tens] Numbers jump when removing 100 or 10 (#7)

Closed #7.
&mdash;Reply to this email directly or view it on GitHub.
