### ISSUE TITLE
New number artwork

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/making-tens#71]
As mentioned in #48 we are changing the numbers to a font with an open license. The new numbers have been emailed to @jonathanolson to implement.

**Comment by jonathanolson** [comment]
Done. I noticed the number 0 was included in the images, but isn't currently used. Is it planned to be used (I'll keep it), or should it be removed?

**Comment by amanda-phet** [comment]
Good point, we do not need a 0! I think it can just be removed.

**Comment by amanda-phet** [comment]
@bethstade we should leave this issue for Jonathan to close after this is implemented and we're happy with the outcome.

**Comment by jonathanolson** [comment]
Removed fully, closing.
