### ISSUE TITLE
PaperNumberModel's constrainPosition

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/making-tens#72]
Usually a method named 'constrainPosition' would indicate that it modifies the object in a mutable way, and 'constrainedPosition' would be a method that would just return a result.

In this case, constrainPosition is always used to set the paper model's destination. I'd recommend constrainPosition keeps its name, but instead of returning the value, it should just modify its destination.

**Comment by AshrafSharf** [comment]
ConstrainPosition sets the destination directly. The function now has another argument which indicates if the constrained destination should be set through animation

**Comment by jonathanolson** [comment]
Looks good, thanks!
