### ISSUE TITLE
Duplication in NumberEntryControl

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/making-tens#76]
This looks like it has a ton of shared code (copy-paste?) with area-builder. Preferably this should be factored out into common code.

@AshrafSharf, what needs had to be added to the area-builder code, and @jbphet are there any objections to moving this to common code?

**Comment by jbphet** [comment]
No objections from me for moving this to common code - seems like the right thing to do.

**Comment by jonathanolson** [comment]
@jbphet, is scenery-phet the correct location, or should this be in sun?

The differences look like:
- READOUT_FONT size changed, will be passed in
- making-tens switched to the value being a string. @jbphet, is the output value preferred to be a number, since you can't write things like "02" anyways? Plan to have the value be numeric internally, will change making-tens to compensate.
- making-tens added setValue, I'd like to keep that.

Let me know, and I'll proceed with the refactoring.

**Comment by jbphet** [comment]
Responses, in order:
+ Passing in the font sounds good
+ My inclination is to say yes, make it a number.  The only time that might be an issue is if decimal places added and the conversion to floating point values was imperfect.  So, unless that thought changes your mind, let's go with making it a number
+ Keeping ```setValue``` sounds good to me

**Comment by jbphet** [comment]
Also, I'd noticed that there was a similar control in the Unit Rates sim, and I just took a look at the code, and there is something called ```KeypadPanelNode``` that seems like it serves essentially the same purpose.  I hate to create more work for you, but it would probably be worthwhile to see if this can also be replaced with the common code version that you're creating.

**Comment by jonathanolson** [comment]
Fixed in commits, added https://github.com/phetsims/unit-rates/issues/130 for discussion about unit-rates' KeypadPanelNode. It had enough differences in behavior and code that I didn't immediately factor it out.
