### ISSUE TITLE
Outlines on Adding screen

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/making-tens#8]
When the keypad is being displayed to edit a number, there should be a dotted ouline where the number will end up after submitting. Once the number is submitted, the outline disappears. 

Right now, the outline only appears on the first number, and it never disappears. 
![screen shot 2015-07-06 at 1 39 25 pm](https://cloud.githubusercontent.com/assets/7852916/8531441/9d1c4058-23e4-11e5-800c-c823d1dd823e.png)

**Comment by AshrafSharf** [comment]
Fixed

**Comment by amanda-phet** [comment]
This looks good. Closing.
