### ISSUE TITLE
Does left-right number balance for the game matter?

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/making-tens#91]
For instance, in the first level:
- ~63% of time time, the left number is greater than the right number
- ~8% of the time, they are equal
- ~28% of the time, the right number is greater than the left number.

Maybe having skewed numbers is good or bad, although I don't remember it being part of the specification.

@amanda-phet and @bethstade, thoughts?

**Comment by bethstade** [comment]
It is suppose to be random.  I am seeing patterns in other levels too, but it's hard to be sure.  Seems to be A LOT of 9 +  8 in level 2 (got 4 in a row!) and 9 + 3's.  Add it SEEMS like it is not uncommon to see flip flops on level 2 - 9 +7 then 7 + 9, but again, I find it hard to be sure I am not imagining.
There is intention to alternate with some of the levels with specific parameters, ( add with 9s, add single and doubles).  No reason first level shouldn't be random.

**Comment by jonathanolson** [comment]
I can check more into other levels.

My presented statistic above was from running the challenge generation 1 million times (first it seemed skewed when exploring the sim manually, and confirmed that the code as written will skew the numbers for the 1st level).

It is "random", but distributed unequally.

**Comment by jonathanolson** [comment]
> But I sometimes think I am seeing patterns in other levels too, but it's hard to be sure. Seems to be A LOT of 9 + 8 in level 2 (got 4 in a row!) and 9 + 3's. Add it SEEMS like it is not uncommon to see flip flops on level 2 - 9 +7 then 7 + 9, but again, I find it hard to be sure I am not imagining.
All of these are fine if it is just from true randomness.

For level 2, it's programmed to always alternate between "left is bigger" and "right is bigger" (non-randomly), but otherwise it is quite random (small number uniformly from 2-9 if on the right, or 2-8 if on the left). There's a very slight bias, but nothing whatsoever to worry about.

**Comment by bethstade** [comment]
thanks for checking!

**Comment by jonathanolson** [comment]
There was only one that was unbalanced like that, and it will be just as simple to have it balanced.

Will proceed with uniform selection!
