### ISSUE TITLE
newBestTime in MakingTensGameModel

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/making-tens#98]
I don't see any other usages of this?

**Comment by bethstade** [comment]
I think the "timer" was a consideration that we might add a timed component at some later iteration of the sim.

**Comment by jonathanolson** [comment]
Understood!

For now, I'd like to have it removed from the code if not used, as it will be very easy to put back in later if we want it.

**Comment by bethstade** [comment]
okay!
